apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gateway-service.fullname" . }}-configmap
data:
  JWT_ACCESS_EXPIRATION: {{ .Values.config.JWT_ACCESS_EXPIRATION | quote }}
  JWT_REFRESH_EXPIRATION: {{ .Values.config.JWT_REFRESH_EXPIRATION | quote }}
  JWT_SECRET_KEY: {{ .Values.config.JWT_SECRET_KEY | quote }}
  SWAGGER_SERVER_URL: {{ .Values.config.SWAGGER_SERVER_URL | quote }}