apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gateway-service.fullname" . }}-configmap
data:
  AI_SERVER_URL: {{ .Values.config.AI_SERVER_URL | quote }}
  EUREKA_PASSWORD: {{ .Values.config.EUREKA_PASSWORD | quote }}
  EUREKA_SERVICE_URL: {{ .Values.config.EUREKA_SERVICE_URL | quote }}
  EUREKA_USERNAME: {{ .Values.config.EUREKA_USERNAME | quote }}
  FLEX_USER_SERVICE_DOMAIN: {{ .Values.config.FLEX_USER_SERVICE_DOMAIN | quote }}
  JWT_ACCESS_EXPIRATION: {{ .Values.config.JWT_ACCESS_EXPIRATION | quote }}
  JWT_REFRESH_EXPIRATION: {{ .Values.config.JWT_REFRESH_EXPIRATION | quote }}
  JWT_SECRET_KEY: {{ .Values.config.JWT_SECRET_KEY | quote }}
  SWAGGER_SERVER_URL: {{ .Values.config.SWAGGER_SERVER_URL | quote }}